/*
* Anderson Miguel
* Hoje começamos a programar java
*/console.log ("Olá mundo!");
//prompt("Digite o seu nome:");


//variaveis
const variavelA = 100;
const variavelB = variavelA + 50;
console.log (variavelB);


let numero = 50;
console.log (numero);
numero = 80;
console.log (numero);

const nome = "Anderson";
const idade = 39;

console.log ("Olá!", "Meu nome é", nome, "e eu tenho", idade, "anos");

//variaveis
const nomex = "Anderson"
const sobrenome = "Miguel"
const idadex = "39"
const estuda1 = "true" 
const estuda2 = "false"

console.log ("Você estuda no SenacRS?", estuda1, estuda2);
console.log ("Meu nome é", nomex, sobrenome, "estou com", idade, "anos");
